services:
  spam_signal:
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.32
    entrypoint: ""
    volumes:
      - .:/home/module
      - bundle:/home/decidim/vendor
      - node_modules:/home/decidim/node_modules
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://decidim:pleaseChangeMe@spam-signal-pg:5432/decidim
      - DATABASE_HOST=spam-signal-pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DEV_MODULE=decidim-spam_signal
      - RAILS_ENV=development
      - DISABLED_DOCKER_COMPOSE=true # To run tests in docker
      - DECIDIM_FORCE_SSL=false
      - DISABLE_SPRING=1
    depends_on:
      spam-signal-pg:
        condition: service_healthy
    ports:
      # Avoid clashing with another process bound to host :3000
      - 3000:3000
      - 3035:3035
    networks:
      - private
      - default

  spam-signal-pg:
    image: postgres:17
    volumes:
      - spam_signal-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=decidim
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pleaseChangeMe
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U decidim"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  node_modules: {}
  bundle: {}
  spam_signal-pg-data: {}

networks:
  private:
    internal: true
