services:
  local_postgres:
    image: postgres:12
    volumes:
      - pg-data-test:/var/lib/postgresql/data
    environment:
      # trunk-ignore(gitleaks/generic-api-key)
      - POSTGRES_PASSWORD=TEST-baeGhi4Ohtahcee5eejoaxaiwaezaiGo
      - POSTGRES_USER=decidim
      - POSTGRES_DB=decidim_test
    ports:
      - 5432:5432
  chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444

volumes:
  pg-data-test: {}
